version: 1.0.{build}
branches:
  only:
#  - master
  - Dev
image: Visual Studio 2022
platform: Any CPU
before_build:
- sh: >-
    - nuget restore

    - choco install opencover.portable

    - choco install codecov
    
build:
  project: TinnyClock.sln
  verbosity: minimal