image: Visual Studio 2022
branches:
  only:
  - master
  
configuration: Release
environment:
  major_version: 1
  minor_version: 7
  patch_version: 0
version: '$(major_version).$(minor_version).$(patch_version).{build}'
dotnet_csproj:
  patch: true
  file: 'TinyMonitorApp\TinyMonitorApp.csproj'
  package_version: '$(major_version).$(minor_version).$(patch_version)'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
before_build: 
  # Display .NET version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore
build_script:
  - cmd: dotnet build -c Release
artifacts:
- path: 'TinyMonitorApp\bin\Release\TinyMonitorApp.exe'
  name: Nuget
 
 deploy:
  release: tinymonitor-v$(APPVEYOR_BUILD_VERSION)
  description: 'Release version'
  provider: GitHub
  auth_token:
    secure: MEUZKpoe3XC1JH4JClPXo/YMsK0kuuZ5uUkzTrZ2OWkYW8wv3Xo2eelty58uti6/
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
 