image: Visual Studio 2022
# configuration for "master" branch

  branches:
    only:
      - Dev
  configuration: Release
  before_build:
    - ps: nuget restore .\TinyMonitor.sln
  build:
    project: .\TinyMonitor.sln
 
 #C:\projects\tinnymonitor-lu1w9\TinyMonitorApp\TinyMonitorApp.csproj