version: 1.0.{build}
nuget:
  project_feed: true
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: TinnyClock\bin\Debug\TinnyClock.exe
  name: TinnyMonitor
