version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2022
nuget:
  project_feed: true
build:
  project: TinyMonitor.sln
  verbosity: minimal
artifacts:
- path: TinyMonitorApp\bin\Release\TinyMonitorApp.exe
  name: TinyMonitor
deploy:
- provider: GitHub
  auth_token:
    secure: yourToken